#index:
#    path: /
#    controller: App\Controller\DefaultController::index

salle_tp_accueil:
  path: /accueil
  controller: App\Controller\SalleController::accueil

salle_tp_afficher:
  path: /afficher/{numero}
  controller: App\Controller\SalleController::afficher
  defaults:
    numero: 0
  requirements:
    numero: \d{1,2}

salle_tp_dix:
  path: /dix
  controller: App\Controller\SalleController::dix
